/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class judgingSystem_SystemTools */

#ifndef _Included_judgingSystem_SystemTools
#define _Included_judgingSystem_SystemTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     judgingSystem_SystemTools
 * Method:    getMemByPID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_judgingSystem_SystemTools_getMemByPID
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
